apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-gateway
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/component: gateway
    app.kubernetes.io/part-of: hr-core
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
      app.kubernetes.io/component: gateway
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Tráfego HTTP só vindo do ingress controller
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: ingress-nginx
      ports:
        - protocol: TCP
          port: 3000
    # /metrics raspado pelo Prometheus
    - from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
          podSelector:
            matchLabels:
              app.kubernetes.io/name: prometheus
      ports:
        - protocol: TCP
          port: 3000
  egress:
    # DNS interno
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: kube-system
          podSelector:
            matchLabels:
              k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Microsserviços downstream no mesmo namespace
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/part-of: hr-core
    # OTLP HTTP exporter (Tempo / OTel Collector)
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: observability
      ports:
        - protocol: TCP
          port: 4318
        - protocol: TCP
          port: 4317
    # JWKS endpoint do Auth Service (HTTPS externo, se aplicável)
    - to: []
      ports:
        - protocol: TCP
          port: 443
