apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: auth
  labels:
    app.kubernetes.io/name: auth
    app.kubernetes.io/component: auth
    app.kubernetes.io/part-of: hr-core
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: auth
      app.kubernetes.io/component: auth
