apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth
  labels:
    app.kubernetes.io/name: auth
    app.kubernetes.io/component: auth
    app.kubernetes.io/part-of: hr-core
automountServiceAccountToken: false
